server:
  servlet:
    context-path: /identity-manager
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
    beans:
      enabled:  false

spring:
  rabbitmq:
    host: 10.72.0.181
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/dtms_v1?useSSL=false
    username: root
    password: root

app:
  service-name: identity-manager service10024