server:
  servlet:
    context-path: /identity-manager
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
    beans:
      enabled:  false

spring:
  rabbitmq:
#    host: https://hornet.rmq.cloudamqp.com/
    host: 52.90.223.165
    port: 15672
    username: admin
    password: admin

app:
  service-name: identity-manager service1000