server:
  servlet:
    context-path: /identity-manager
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
    beans:
      enabled:  false

spring:
  rabbitmq:
    host: 10.72.0.181
    port: 5672
#    username: fnfteam111
#    password: A12345678!a

app:
  service-name: identity-manager service1000